# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-02 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authors',
            field=models.CharField(max_length=200),
        ),
    ]
